// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AboutMeDocumentDataSlicesSlice = RichTextBlockSlice;

/**
 * Content for About me documents
 */
interface AboutMeDocumentData {
  /**
   * Slice Zone field in *About me*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutMeDocumentDataSlicesSlice>; /**
   * Meta Title field in *About me*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_me.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About me*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_me.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About me*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About me document from Prismic
 *
 * - **API ID**: `about_me`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutMeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutMeDocumentData>,
    "about_me",
    Lang
  >;

type ColophonDocumentDataSlicesSlice = RichTextBlockSlice;

/**
 * Content for colophon documents
 */
interface ColophonDocumentData {
  /**
   * Slice Zone field in *colophon*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: colophon.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ColophonDocumentDataSlicesSlice>; /**
   * Meta Title field in *colophon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: colophon.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *colophon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: colophon.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *colophon*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: colophon.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * colophon document from Prismic
 *
 * - **API ID**: `colophon`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ColophonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ColophonDocumentData>,
    "colophon",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | EducationSectionSlice
  | ProjectGallerySlice
  | ContactSectionSlice
  | HeaderSlice
  | RichTextBlockSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type JournelCatalogDocumentDataSlicesSlice = BlogSectionSlice;

/**
 * Content for Journel Catalog documents
 */
interface JournelCatalogDocumentData {
  /**
   * Slice Zone field in *Journel Catalog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: journel_catalog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<JournelCatalogDocumentDataSlicesSlice>; /**
   * Meta Title field in *Journel Catalog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: journel_catalog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Journel Catalog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: journel_catalog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Journel Catalog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: journel_catalog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Journel Catalog document from Prismic
 *
 * - **API ID**: `journel_catalog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JournelCatalogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<JournelCatalogDocumentData>,
    "journel_catalog",
    Lang
  >;

type JournelEntryDocumentDataSlicesSlice = RichTextBlockSlice;

/**
 * Content for Journel Entry documents
 */
interface JournelEntryDocumentData {
  /**
   * Slice Zone field in *Journel Entry*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: journel_entry.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<JournelEntryDocumentDataSlicesSlice>; /**
   * Meta Title field in *Journel Entry*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: journel_entry.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Journel Entry*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: journel_entry.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Journel Entry*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: journel_entry.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Journel Entry document from Prismic
 *
 * - **API ID**: `journel_entry`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JournelEntryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<JournelEntryDocumentData>,
    "journel_entry",
    Lang
  >;

type NowPageDocumentDataSlicesSlice = BentoBoxSlice;

/**
 * Content for now page documents
 */
interface NowPageDocumentData {
  /**
   * Slice Zone field in *now page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: now_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<NowPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *now page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: now_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *now page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: now_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *now page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: now_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * now page document from Prismic
 *
 * - **API ID**: `now_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NowPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NowPageDocumentData>,
    "now_page",
    Lang
  >;

type ProjectDocumentDataSlicesSlice = RichTextBlockSlice;

/**
 * Content for project documents
 */
interface ProjectDocumentData {
  /**
   * Slice Zone field in *project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice>; /**
   * Meta Title field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

type ProjectsCatalogDocumentDataSlicesSlice = ProjectGallerySlice;

/**
 * Content for Projects Catalog documents
 */
interface ProjectsCatalogDocumentData {
  /**
   * Slice Zone field in *Projects Catalog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_catalog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProjectsCatalogDocumentDataSlicesSlice>; /**
   * Meta Title field in *Projects Catalog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: projects_catalog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Projects Catalog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: projects_catalog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Projects Catalog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_catalog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Projects Catalog document from Prismic
 *
 * - **API ID**: `projects_catalog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsCatalogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProjectsCatalogDocumentData>,
    "projects_catalog",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * nav Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].nav_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  nav_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * ThemeSwtich field in *Settings → Navigation*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.navigation[].themeswtich
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  themeswtich: prismic.BooleanField;
}

/**
 * Item in *Settings → footer*
 */
export interface SettingsDocumentDataFooterItem {
  /**
   * date time field in *Settings → footer*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer[].date_time
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  date_time: prismic.TimestampField;

  /**
   * location field in *Settings → footer*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer[].location
   * - **Documentation**: https://prismic.io/docs/fields/geopoint
   */
  location: prismic.GeoPointField;

  /**
   * footer link field in *Settings → footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer[].footer_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  footer_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

type SettingsDocumentDataSlicesSlice = never;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: toonchavez
   * - **API ID Path**: settings.site_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_name: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * footer field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer: prismic.GroupField<Simplify<SettingsDocumentDataFooterItem>>;

  /**
   * `slices` field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | AboutMeDocument
  | ColophonDocument
  | HomepageDocument
  | JournelCatalogDocument
  | JournelEntryDocument
  | NowPageDocument
  | ProjectDocument
  | ProjectsCatalogDocument
  | SettingsDocument;

/**
 * Item in *NowFeed → Default → Primary → Bento Section*
 */
export interface BentoBoxSliceDefaultPrimaryBentoSectionItem {
  /**
   * bento img field in *NowFeed → Default → Primary → Bento Section*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.bento_section[].bento_img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bento_img: prismic.ImageField<never>;

  /**
   * Bento header field in *NowFeed → Default → Primary → Bento Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.bento_section[].bento_header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  bento_header: prismic.KeyTextField;

  /**
   * Bento Body field in *NowFeed → Default → Primary → Bento Section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.bento_section[].bento_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bento_body: prismic.RichTextField;

  /**
   * Now Link field in *NowFeed → Default → Primary → Bento Section*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.bento_section[].now_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  now_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * NowUpdate field in *NowFeed → Default → Primary → Bento Section*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.bento_section[].nowupdate
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  nowupdate: prismic.DateField;

  /**
   * Bento Icon field in *NowFeed → Default → Primary → Bento Section*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select
   * - **Default Value**: General
   * - **API ID Path**: bento_box.default.primary.bento_section[].bento_icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bento_icon: prismic.SelectField<
    | "General"
    | "Dev"
    | "Life"
    | "Love"
    | "Cooking"
    | "DND"
    | "Reading"
    | "Writing"
    | "Family"
    | "Learning",
    "filled"
  >;
}

/**
 * Primary content in *NowFeed → Default → Primary*
 */
export interface BentoBoxSliceDefaultPrimary {
  /**
   * Sectiontittle field in *NowFeed → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: // What i'm doing?
   * - **API ID Path**: bento_box.default.primary.sectiontittle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sectiontittle: prismic.KeyTextField;

  /**
   * Bento Section field in *NowFeed → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.bento_section[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  bento_section: prismic.GroupField<
    Simplify<BentoBoxSliceDefaultPrimaryBentoSectionItem>
  >;

  /**
   * Updated Date field in *NowFeed → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.updated_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  updated_date: prismic.DateField;
}

/**
 * Default variation for NowFeed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoBoxSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BentoBoxSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NowFeed*
 */
type BentoBoxSliceVariation = BentoBoxSliceDefault;

/**
 * NowFeed Shared Slice
 *
 * - **API ID**: `bento_box`
 * - **Description**: BentoBox
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoBoxSlice = prismic.SharedSlice<
  "bento_box",
  BentoBoxSliceVariation
>;

/**
 * Item in *BlogSection → Default → Primary → Blog section*
 */
export interface BlogSectionSliceDefaultPrimaryBlogSectionItem {
  /**
   * Blog tittle field in *BlogSection → Default → Primary → Blog section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.default.primary.blog_section[].blog_tittle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  blog_tittle: prismic.KeyTextField;

  /**
   * Blog Description field in *BlogSection → Default → Primary → Blog section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.default.primary.blog_section[].blog_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  blog_description: prismic.KeyTextField;

  /**
   * blog image field in *BlogSection → Default → Primary → Blog section*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.default.primary.blog_section[].blog_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  blog_image: prismic.ImageField<never>;

  /**
   * Blog link field in *BlogSection → Default → Primary → Blog section*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.default.primary.blog_section[].blog_link
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  blog_link: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * posted field in *BlogSection → Default → Primary → Blog section*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.default.primary.blog_section[].posted
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  posted: prismic.DateField;
}

/**
 * Primary content in *BlogSection → Default → Primary*
 */
export interface BlogSectionSliceDefaultPrimary {
  /**
   * Sectiontittle field in *BlogSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.default.primary.sectiontittle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sectiontittle: prismic.KeyTextField;

  /**
   * Blog section field in *BlogSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.default.primary.blog_section[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  blog_section: prismic.GroupField<
    Simplify<BlogSectionSliceDefaultPrimaryBlogSectionItem>
  >;
}

/**
 * Default variation for BlogSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogSection*
 */
type BlogSectionSliceVariation = BlogSectionSliceDefault;

/**
 * BlogSection Shared Slice
 *
 * - **API ID**: `blog_section`
 * - **Description**: BlogSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogSectionSlice = prismic.SharedSlice<
  "blog_section",
  BlogSectionSliceVariation
>;

/**
 * Item in *ContactSection → Default → Primary → Social Media Links*
 */
export interface ContactSectionSliceDefaultPrimarySocialMediaLinksItem {
  /**
   * Social Media Link field in *ContactSection → Default → Primary → Social Media Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.social_media_links[].social_media_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_media_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *ContactSection → Default → Primary*
 */
export interface ContactSectionSliceDefaultPrimary {
  /**
   * Sectiontittle field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.sectiontittle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sectiontittle: prismic.KeyTextField;

  /**
   * Section Body field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.section_body
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_body: prismic.KeyTextField;

  /**
   * Social Media Links field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.social_media_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_media_links: prismic.GroupField<
    Simplify<ContactSectionSliceDefaultPrimarySocialMediaLinksItem>
  >;

  /**
   * Email field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;
}

/**
 * Default variation for ContactSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactSection*
 */
type ContactSectionSliceVariation = ContactSectionSliceDefault;

/**
 * ContactSection Shared Slice
 *
 * - **API ID**: `contact_section`
 * - **Description**: ContactSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSlice = prismic.SharedSlice<
  "contact_section",
  ContactSectionSliceVariation
>;

/**
 * Item in *EducationSection → Default → Primary → Schools Dropdown*
 */
export interface EducationSectionSliceDefaultPrimarySchoolsDropdownItem {
  /**
   * School Name field in *EducationSection → Default → Primary → Schools Dropdown*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education_section.default.primary.schools_dropdown[].school_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  school_name: prismic.KeyTextField;

  /**
   * Start Date field in *EducationSection → Default → Primary → Schools Dropdown*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: education_section.default.primary.schools_dropdown[].start_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  start_date: prismic.DateField;

  /**
   * End Date field in *EducationSection → Default → Primary → Schools Dropdown*
   *
   * - **Field Type**: Date
   * - **Placeholder**: End Date
   * - **API ID Path**: education_section.default.primary.schools_dropdown[].end_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  end_date: prismic.DateField;

  /**
   * Currently Enrolled field in *EducationSection → Default → Primary → Schools Dropdown*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: education_section.default.primary.schools_dropdown[].currently_enrolled
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  currently_enrolled: prismic.BooleanField;

  /**
   * School Body field in *EducationSection → Default → Primary → Schools Dropdown*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education_section.default.primary.schools_dropdown[].school_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  school_body: prismic.RichTextField;
}

/**
 * Primary content in *EducationSection → Default → Primary*
 */
export interface EducationSectionSliceDefaultPrimary {
  /**
   * Sectiontittle field in *EducationSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: education_section.default.primary.sectiontittle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sectiontittle: prismic.KeyTextField;

  /**
   * Schools Dropdown field in *EducationSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: education_section.default.primary.schools_dropdown[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  schools_dropdown: prismic.GroupField<
    Simplify<EducationSectionSliceDefaultPrimarySchoolsDropdownItem>
  >;
}

/**
 * Default variation for EducationSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EducationSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EducationSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EducationSection*
 */
type EducationSectionSliceVariation = EducationSectionSliceDefault;

/**
 * EducationSection Shared Slice
 *
 * - **API ID**: `education_section`
 * - **Description**: EducationSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EducationSectionSlice = prismic.SharedSlice<
  "education_section",
  EducationSectionSliceVariation
>;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Location field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Location Geo field in *Footer → Default → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.location_geo
   * - **Documentation**: https://prismic.io/docs/fields/geopoint
   */
  location_geo: prismic.GeoPointField;

  /**
   * Footer Link field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footer_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  footer_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * Name field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Position field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Fullstack dev
   * - **API ID Path**: header.default.primary.position
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  position: prismic.KeyTextField;

  /**
   * Last updated field in *Header → Default → Primary*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.last_updated
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  last_updated: prismic.TimestampField;

  /**
   * Header Body field in *Header → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.header_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  header_body: prismic.RichTextField;

  /**
   * Profile Image field in *Header → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.profile_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  profile_image: prismic.ImageField<never>;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Item in *ProjectGallery → Default → Primary → Project Byte*
 */
export interface ProjectGallerySliceDefaultPrimaryProjectByteItem {
  /**
   * project image field in *ProjectGallery → Default → Primary → Project Byte*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.project_byte[].project_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  project_image: prismic.ImageField<never>;

  /**
   * project date field in *ProjectGallery → Default → Primary → Project Byte*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.project_byte[].project_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  project_date: prismic.DateField;

  /**
   * Project Name field in *ProjectGallery → Default → Primary → Project Byte*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.project_byte[].project_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_name: prismic.KeyTextField;

  /**
   * Project Description field in *ProjectGallery → Default → Primary → Project Byte*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.project_byte[].project_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_description: prismic.KeyTextField;

  /**
   * Project Tags field in *ProjectGallery → Default → Primary → Project Byte*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.project_byte[].project_tags
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_tags: prismic.KeyTextField;

  /**
   * Live link field in *ProjectGallery → Default → Primary → Project Byte*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to live site
   * - **API ID Path**: project_gallery.default.primary.project_byte[].live_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  live_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Repo Link field in *ProjectGallery → Default → Primary → Project Byte*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to repo
   * - **API ID Path**: project_gallery.default.primary.project_byte[].repo_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  repo_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Project Link field in *ProjectGallery → Default → Primary → Project Byte*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.project_byte[].project_link
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  project_link: prismic.ContentRelationshipField<"project">;

  /**
   * featured field in *ProjectGallery → Default → Primary → Project Byte*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project_gallery.default.primary.project_byte[].featured
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;
}

/**
 * Primary content in *ProjectGallery → Default → Primary*
 */
export interface ProjectGallerySliceDefaultPrimary {
  /**
   * Sectiontittle field in *ProjectGallery → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.sectiontittle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sectiontittle: prismic.KeyTextField;

  /**
   * Project Byte field in *ProjectGallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.default.primary.project_byte[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  project_byte: prismic.GroupField<
    Simplify<ProjectGallerySliceDefaultPrimaryProjectByteItem>
  >;
}

/**
 * Default variation for ProjectGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectGallery*
 */
type ProjectGallerySliceVariation = ProjectGallerySliceDefault;

/**
 * ProjectGallery Shared Slice
 *
 * - **API ID**: `project_gallery`
 * - **Description**: ProjectGallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectGallerySlice = prismic.SharedSlice<
  "project_gallery",
  ProjectGallerySliceVariation
>;

/**
 * Primary content in *RichTextBlock → Default → Primary*
 */
export interface RichTextBlockSliceDefaultPrimary {
  /**
   * rich text field in *RichTextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text_block.default.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  rich_text: prismic.RichTextField;
}

/**
 * Default variation for RichTextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichTextBlock*
 */
type RichTextBlockSliceVariation = RichTextBlockSliceDefault;

/**
 * RichTextBlock Shared Slice
 *
 * - **API ID**: `rich_text_block`
 * - **Description**: RichTextBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextBlockSlice = prismic.SharedSlice<
  "rich_text_block",
  RichTextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutMeDocument,
      AboutMeDocumentData,
      AboutMeDocumentDataSlicesSlice,
      ColophonDocument,
      ColophonDocumentData,
      ColophonDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      JournelCatalogDocument,
      JournelCatalogDocumentData,
      JournelCatalogDocumentDataSlicesSlice,
      JournelEntryDocument,
      JournelEntryDocumentData,
      JournelEntryDocumentDataSlicesSlice,
      NowPageDocument,
      NowPageDocumentData,
      NowPageDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      ProjectsCatalogDocument,
      ProjectsCatalogDocumentData,
      ProjectsCatalogDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SettingsDocumentDataFooterItem,
      SettingsDocumentDataSlicesSlice,
      AllDocumentTypes,
      BentoBoxSlice,
      BentoBoxSliceDefaultPrimaryBentoSectionItem,
      BentoBoxSliceDefaultPrimary,
      BentoBoxSliceVariation,
      BentoBoxSliceDefault,
      BlogSectionSlice,
      BlogSectionSliceDefaultPrimaryBlogSectionItem,
      BlogSectionSliceDefaultPrimary,
      BlogSectionSliceVariation,
      BlogSectionSliceDefault,
      ContactSectionSlice,
      ContactSectionSliceDefaultPrimarySocialMediaLinksItem,
      ContactSectionSliceDefaultPrimary,
      ContactSectionSliceVariation,
      ContactSectionSliceDefault,
      EducationSectionSlice,
      EducationSectionSliceDefaultPrimarySchoolsDropdownItem,
      EducationSectionSliceDefaultPrimary,
      EducationSectionSliceVariation,
      EducationSectionSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeaderSlice,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      ProjectGallerySlice,
      ProjectGallerySliceDefaultPrimaryProjectByteItem,
      ProjectGallerySliceDefaultPrimary,
      ProjectGallerySliceVariation,
      ProjectGallerySliceDefault,
      RichTextBlockSlice,
      RichTextBlockSliceDefaultPrimary,
      RichTextBlockSliceVariation,
      RichTextBlockSliceDefault,
    };
  }
}
