import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import './globals.css';
import { NavBar } from './ui/NavBar/NavBar';
import { Footer } from './ui/Footer/Footer';
import { Providers } from './providers';

export const metadata: Metadata = {
    title: {
        template: '%s | Toonchavez.dev',
        default: 'Toonchavez.dev'
    },
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${GeistSans.variable} ${GeistMono.variable} relative `}
            suppressHydrationWarning>
            <Providers>
                <body className="relative min-h-screen bg-base-200 px-4 pt-4  text-neutral antialiased dark:bg-neutral dark:text-base-100">
                    <NavBar />
                    {children}
                    <Footer />
                </body>
            </Providers>
        </html>
    );
}
