// Code generated by Prismic. DO NOT EDIT.

import NowFeed from "./NowFeed";
import BlogSection from "./BlogSection";
import ContactSection from "./ContactSection";
import EducationSection from "./EducationSection";
import Footer from "./Footer";
import Header from "./Header";
import ProjectGallery from "./ProjectGallery";
import RichTextBlock from "./RichTextBlock";

export const components = {
	bento_box: NowFeed,
	blog_section: BlogSection,
	contact_section: ContactSection,
	education_section: EducationSection,
	footer: Footer,
	header: Header,
	project_gallery: ProjectGallery,
	rich_text_block: RichTextBlock
};